---
title: "Improvement of chromVAR - comparison between "
author: "Jiayi Wang"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
format:
  html:
    toc: true
    code-fold: true
    code-tools: true
    toc_float: true

output:
  quarto::quarto_html:
    output_dir: "../docs/"
---

## Dependencies
```{r set up, message=FALSE, warning=FALSE}
suppressPackageStartupMessages({
    library(chromVAR)
    library(motifmatchr)
    library(Matrix)
    library(SummarizedExperiment)
    library(BiocParallel)
    library(BSgenome.Hsapiens.UCSC.hg38)
    library(ggplot2)
    library(JASPAR2016)
    library(pheatmap)
    library(patchwork)
    library(limma)
    library(stringr)
    library(data.table)
    library(ggpubr)
    library(csaw)
    source("utils.R")
})
set.seed(2017)

```


## Load simulated data
```{r data}
files <- list.files("../data/01a_sim", "*.rds", full.names = TRUE)
sims <- lapply(files, readRDS)
names(sims) <- c("0", "0.25", "0.5", "1", "3")
motifs <- getNonRedundantMotifs(format = "PFMatrix", species = "Hsapiens")
```

## Apply chromVAR on only low accessible peaks

### z-score

::: {.panel-tabset}

### <= 25% quantile
```{r 25 quantile, fig.height=15, fig.width=10}
# devs_thr25 <- lapply(sims, \(x) {
#     rm <- apply(counts(x), 1, min)
#     thr <- quantile(rm)[2]
#     if (thr == 0) thr = 1
#     idx <- which(rm <= thr)
#     x <- x[idx, ]
#     dev <- .chromVAR_bulk(x,
#     motifs,
#     BSgenome.Hsapiens.UCSC.hg38,
#     TRUE)
# })
# 
# saveRDS(devs_thr25, "../result/01_sim/devs_thr25.rds")
devs_thr25 <- readRDS("../result/01_sim/devs_thr25.rds")
lapply(names(devs_thr25), \(x) {
    dev <- devs_thr25[[x]]
    df <- sechm::meltSE(dev, row.names(dev))
    df$chip <- addChIP(df$feature)
    ggplot(df, aes(z, colour = sample)) +
        geom_density() + ggtitle(paste0("Effect: ", x)) + 
        facet_grid(~ chip) +
    geom_vline(xintercept = 0, linetype="dashed", 
                  color = "black", size=0.5, alpha = 0.8)
})  |>  wrap_plots(ncol = 1) +  plot_layout(guides = "collect")

```

### Peaks with rowMins <= 50% quantile
```{r 50 quantile, fig.height=15, fig.width=10}
# devs_thr50 <- lapply(sims, \(x) {
#     rm <- apply(counts(x), 1, min)
#     thr <- quantile(rm)[3]
#     if (thr == 0) thr = 1
#     idx <- which(rm <= thr)
#     x <- x[idx, ]
#     dev <- .chromVAR_bulk(x,
#     motifs,
#     BSgenome.Hsapiens.UCSC.hg38,
#     TRUE)
# })
# 
# saveRDS(devs_thr50, "../result/01_sim/devs_thr50.rds")
devs_thr50 <- readRDS("../result/01_sim/devs_thr50.rds")
lapply(names(devs_thr50), \(x) {
    dev <- devs_thr50[[x]]
    df <- sechm::meltSE(dev, row.names(dev))
    df$chip <- addChIP(df$feature)
    ggplot(df, aes(z, colour = sample)) +
        geom_density() + ggtitle(paste0("Effect: ", x)) + 
        facet_grid(~ chip) +
    geom_vline(xintercept = 0, linetype="dashed", 
                  color = "black", size=0.5, alpha = 0.8)
})  |>  wrap_plots(ncol = 1) +  plot_layout(guides = "collect")

```

### <= 75% quantile
```{r 75 quantile, fig.height=15, fig.width=10}
# devs_thr75 <- lapply(sims, \(x) {
#     rm <- apply(counts(x), 1, min)
#     thr <- quantile(rm)[4]
#     if (thr == 0) thr = 1
#     idx <- which(rm <= thr)
#     x <- x[idx, ]
#     dev <- .chromVAR_bulk(x,
#     motifs,
#     BSgenome.Hsapiens.UCSC.hg38,
#     TRUE)
# })
# 
# saveRDS(devs_thr75, "../result/01_sim/devs_thr75.rds")
devs_thr75 <- readRDS("../result/01_sim/devs_thr75.rds")
lapply(names(devs_thr50), \(x) {
    dev <- devs_thr50[[x]]
    df <- sechm::meltSE(dev, row.names(dev))
    df$chip <- addChIP(df$feature)
    ggplot(df, aes(z, colour = sample)) +
        geom_density() + ggtitle(paste0("Effect: ", x)) + 
        facet_grid(~ chip) +
    geom_vline(xintercept = 0, linetype="dashed", 
                  color = "black", size=0.5, alpha = 0.8)
})  |>  wrap_plots(ncol = 1) +  plot_layout(guides = "collect")

```

### <= 100% quantile: all
```{r z-dist old, fig.height=15, fig.width=10}
old_devs <- readRDS("../result/01_sim/old_devs.rds")
lapply(names(old_devs), \(x) {
    dev <- old_devs[[x]]
    df <- sechm::meltSE(dev, row.names(dev))
    df$chip <- addChIP(df$feature)
    ggplot(df, aes(z, colour = sample)) +
        geom_density() + ggtitle(paste0("Effect: ", x)) + 
        facet_grid(~ chip) +
    geom_vline(xintercept = 0, linetype="dashed", 
                  color = "black", size=0.5, alpha = 0.8)
})  |>  wrap_plots(ncol = 1) +  plot_layout(guides = "collect")
```

:::

## Differential analysis on z-score
```{r limma, message=FALSE, warning=FALSE}
applyLimma <- \(devs, assay.id = "z") {
  res <- lapply(devs, \(dev) {
    colData(dev)$group_id <- substr(colnames(dev), 1, nchar(colnames(dev)) - 5)
    design <- model.matrix(~ dev$group_id)
    fit <- eBayes(lmFit(assay(dev, assay.id), design))
    res <- topTable(fit, n = Inf)
    ids <- match(rownames(res), rownames(dev))
    res$name <- rowData(dev)$name[ids]
    res 
    })
  names(res) <-  c("0", "0.25", "0.5", "1", "3")
  res
}
limma_thr25 <- applyLimma(devs_thr25) 
limma_thr50 <- applyLimma(devs_thr50)
limma_thr75 <- applyLimma(devs_thr75)
limma_thr100 <- applyLimma(old_devs)

lfc <- lapply(names(limma_thr25), \(x) {
    thr25 <- data.frame(limma_thr25[[x]], effect = x, threshold = "25%")
    thr50 <- data.frame(limma_thr50[[x]], effect = x, threshold = "50%")
    thr75 <- data.frame(limma_thr75[[x]], effect = x, threshold = "75%")
    thr100 <- data.frame(limma_thr100[[x]], effect = x, threshold = "100%")
    do.call(rbind, list(thr25, thr50, thr75, thr100))
})
lfc <- do.call(rbind, lfc)
lfc$chip <- addChIP(rownames(lfc))
```

### Histogram of logFC
```{r lfc histo, fig.height=12, fig.width=12}
ggplot(lfc, aes(x = logFC, col = chip)) + 
    geom_histogram(aes(y = after_stat(density)),      
        fill = "white",
        bins = 30,
        alpha = 0.2) +
    geom_density(alpha = 0.2) + 
    facet_grid(threshold ~ effect, scales = "free")
```

### Violin plot of logFC
::: {.panel-tabset}

### Group by ChIP overlapping
```{r lfc violin, fig.height=12, fig.width=12}
ggplot(lfc, aes(x = factor(chip), y = logFC, fill = threshold)) +
  geom_violin(alpha = 0.5) +
  geom_boxplot(width = 0.2, position = position_dodge(0.9), alpha = 0.4) +
  scale_fill_brewer(palette = "Blues") +
  facet_wrap(~ effect, ncol = 2, labeller = \(.) label_both(.), scales="free") +
  xlab("ChIP-seq overlaps")
```

### Group by threshold
```{r lfc violin2, fig.height=12, fig.width=12, warning=FALSE, message=FALSE}
ggplot(lfc, aes(x = factor(threshold), y = logFC, fill = chip)) +
  geom_violin(alpha = 0.5) +
  geom_boxplot(width = 0.2, position = position_dodge(0.9), alpha = 0.4) +
  scale_fill_brewer(palette = "Blues") +
  facet_wrap(~ effect, ncol = 2, labeller = \(.) label_both(.), scales="free") +
  xlab("ChIP-seq overlaps")
```

:::

### t-statistics of CEBPB
```{r t-stat, fig.height=8, fig.width=8}
df <- lfc[str_detect(lfc$name, "CEBPB"),]
ggplot(df, aes(x = effect, y = t, group = threshold,
    label = t, color = threshold)) +
    geom_line(linetype = "dashed") +
    geom_point() +
    facet_grid(threshold ~ chip, scales = "free") 
```



