---
title: "Improvement of chromVAR - data with significant technical issues"
author: "Jiayi Wang"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
format:
  html:
    toc: true
    code-fold: true
    code-tools: true
    toc_float: true

output:
  quarto::quarto_html:
    output_dir: "../docs/"
---

## Dependencies
```{r set up, message=FALSE, warning=FALSE}
suppressPackageStartupMessages({
    library(chromVAR)
    library(motifmatchr)
    library(Matrix)
    library(SummarizedExperiment)
    library(BiocParallel)
    # library(BSgenome.Hsapiens.UCSC.hg19)
    library(BSgenome.Mmusculus.UCSC.mm10)
    library(ggplot2)
    library(pheatmap)
    library(patchwork)
    library(limma)
    library(stringr)
    library(ggpubr)
    library(csaw)
    library(qsmooth)
    source("utils.R")
})
set.seed(2017)

```

## Load real data
```{r data, message=FALSE, warning=FALSE}
dat <- readRDS("../data/03_technical/caradonna.subset.peakCounts.rds")
seqlevelsStyle(dat) <- "UCSC"
dat <- keepStandardChromosomes(dat, 
  species="Mus_musculus", 
  pruning.mode="coarse")
```

## Run ChromVAR with different similarity parameters
```{r chromVAR, message=FALSE, warning=FALSE}
motifs <- getNonRedundantMotifs(format = "PFMatrix", species = "Mmusculus")
# w <- c(0.0001, 0.001, 0.01, 0.05, 0.1)
# wRes <- lapply(w, \(wi) {
#     x <- filterPeaks(dat, non_overlapping = TRUE)
#     x <- addGCBias(x,
#         genome =  BSgenome.Mmusculus.UCSC.mm10)
#     bg <- getBackgroundPeaks(object = x, niterations = 1500, w = wi)
#     motif_ix <- matchMotifs(motifs,
#         x,
#         genome =  BSgenome.Mmusculus.UCSC.mm10)
#     dev <- computeDeviations(object = x,
#         annotations = motif_ix,
#         background_peaks = bg
#         )
# })
# names(wRes) <- as.character(w)
# saveRDS(wRes, "../result/02_dat/tech_wRes.rds")
wRes <- readRDS("../result/02_dat/tech_wRes.rds")
```


### z-score curve

::: {.panel-tabset}
### z-score
```{r wRes, fig.height=10, fig.width=13}
lapply(names(wRes), \(x) {
    dev <- wRes[[x]]
    df <- sechm::meltSE(dev, row.names(dev))
    ggplot(df, aes(z, colour = sample)) +
        geom_density() + ggtitle(paste0("similarity: ", x)) 
})  |>  wrap_plots(ncol = 2) +  plot_layout(guides = "collect")
```

### deviations
```{r wRes dev, fig.height=10, fig.width=13}
lapply(names(wRes), \(x) {
    dev <- wRes[[x]]
    df <- sechm::meltSE(dev, row.names(dev))
    ggplot(df, aes(deviations, colour = sample)) +
        geom_density() + ggtitle(paste0("similarity: ", x)) 
})  |>  wrap_plots(ncol = 2) +  plot_layout(guides = "collect")
```


:::

### csaw on z-score
```{r csaw, fig.height=8, fig.width=13}
dev <- wRes[["1e-04"]]
csaw <- dev
assay(csaw, "z") <- exp(assay(dev, "z"))
csaw$totals <- colSums(assay(csaw, "z"))
csaw <- normOffsets(csaw, assay.id = "z")
ggplot(sechm::meltSE(csaw, row.names(dev)), aes(offset, colour = sample)) +
        geom_density()
```

### csaw on deviations
```{r csaw devs, fig.height=8, fig.width=13}
dev <- wRes[["1e-04"]]
csaw <- dev
assay(csaw, "deviations") <- exp(assay(dev, "deviations"))
csaw$totals <- colSums(assay(csaw, "deviations"))
csaw <- normOffsets(csaw, assay.id = "deviations")
ggplot(sechm::meltSE(csaw, row.names(dev)), aes(offset, colour = sample)) +
        geom_density()
```


### GC-content smooth quantile normalization
```{r gcqn}
# get GC content
rn <- rownames(dat)
names <- strsplit(rn, "[:-]")
sn <- unlist(lapply(names,\(.) paste0("chr",.[1])))
start <- as.numeric(unlist(lapply(names,\(.) .[2])))
end <- as.numeric(unlist(lapply(names,\(.) .[3])))
sn[which(sn == "chrMT")] <- "chrM"
gr <- GRanges(seqnames=sn, 
  ranges=IRanges(start, end), 
  strand="-",
  mcols=data.frame(peakID=rn))
peakSeqs <- getSeq(x = BSgenome.Mmusculus.UCSC.mm10, gr)
gcContentPeaks <- letterFrequency(peakSeqs, "GC",as.prob=TRUE)[,1]
gcGroups <- Hmisc::cut2(gcContentPeaks, g=20)
mcols(gr)$gc <- gcContentPeaks

## GCQN
# countsTFiltGCQN <- gcqn(counts(dat), gcGroups, summary="median", round=TRUE)
# cpmGCQN <- edgeR::cpm(countsTFiltGCQN, normalized.lib.sizes=FALSE, log=FALSE, prior.count=0.25)
# x <- dat
# counts(x) <- cpmGCQN
# x <- filterPeaks(x, non_overlapping = TRUE)
# x <- addGCBias(x,
#         genome =  BSgenome.Mmusculus.UCSC.mm10)
# bg <- getBackgroundPeaks(object = x, niterations = 1500, w = 0.0001)
# motif_ix <- matchMotifs(motifs, x,
#         genome =  BSgenome.Mmusculus.UCSC.mm10)
# gcqn_devs <- computeDeviations(object = x,
#         annotations = motif_ix,
#         background_peaks = bg
#         )
# gcqn_devs <- saveRDS(gcqn_devs, "../result/02_dat/tech_GCQNdevs.rds")
gcqn_devs <- readRDS("../result/02_dat/tech_GCQNdevs.rds")

## GCQN smooth
# smoothGCQN <-  gcqn_qsmooth(counts(dat), gcGroups,
#   bio=droplevels(colData(dat)$condition))
# x <- dat
# counts(x) <- smoothGCQN
# x <- filterPeaks(x, non_overlapping = TRUE)
# x <- addGCBias(x,
#         genome =  BSgenome.Mmusculus.UCSC.mm10)
# bg <- getBackgroundPeaks(object = x, niterations = 1500, w = 0.0001)
# motif_ix <- matchMotifs(motifs, x,
#         genome =  BSgenome.Mmusculus.UCSC.mm10)
# Sgcqn_devs <- computeDeviations(object = x,
#         annotations = motif_ix,
#         background_peaks = bg
#         )
# Sgcqn_devs <- saveRDS(Sgcqn_devs, "../result/02_dat/tech_SmoothGCQNdevs.rds")
Sgcqn_devs <- readRDS("../result/02_dat/tech_SmoothGCQNdevs.rds")
```

### TMM
```{r TMM, fig.height=10, fig.width=15}
devtools::load_all("../../chromVAR/")
source("utils.R")
x <- filterPeaks(dat, non_overlapping = TRUE)
x <- addGCBias(x,
        genome =  BSgenome.Mmusculus.UCSC.mm10)
bg <- getBackgroundPeaks(object = x, niterations = 1500, w = 0.0001)
motif_ix <- matchMotifs(motifs, x,
        genome =  BSgenome.Mmusculus.UCSC.mm10)
TMM_devs <- computeDeviations(object = x,
        annotations = motif_ix,
        background_peaks = bg
        )
TMM_devs <- saveRDS(TMM_devs, "../result/02_dat/tech_TMMdevs.rds")
TMM_devs <- readRDS("../result/02_dat/tech_TMMdevs.rds")
p1 <- ggplot(sechm::meltSE(dev, row.names(dev)), aes(z, colour = sample)) +
        geom_density() +
        ggtitle("standard chromVAR") + 
        geom_vline(xintercept = 0, linetype="dashed", 
                  color = "black", size=0.5, alpha = 0.8)

p2 <- ggplot(sechm::meltSE(TMM_devs, row.names(TMM_devs)), aes(z, colour = sample)) +
        geom_density() +
        ggtitle("TMM") + 
        geom_vline(xintercept = 0, linetype="dashed", 
                  color = "black", size=0.5, alpha = 0.8)

p3 <- ggplot(sechm::meltSE(gcqn_devs, row.names(gcqn_devs)), aes(z, colour = sample)) +
        geom_density() +
        ggtitle("GCQN") + 
        geom_vline(xintercept = 0, linetype="dashed", 
                  color = "black", size=0.5, alpha = 0.8)

p4 <- ggplot(sechm::meltSE(Sgcqn_devs, row.names(gcqn_devs)), aes(z, colour = sample)) +
        geom_density() +
        ggtitle("GC smooth quantile") + 
        geom_vline(xintercept = 0, linetype="dashed", 
                  color = "black", size=0.5, alpha = 0.8)


list(p1, p2, p3, p4) |> wrap_plots(ncol = 2) + plot_layout(guides = "collect") 
```



## logFC comparison

### logFC on original 
```{r limma}
## original devs
colData(dev)$group_id <- substr(colnames(dev), 1, nchar(colnames(dev)) - 5)
design <- model.matrix(~ dev$group_id)
fit <- eBayes(lmFit(assays(dev)$z, design))
res <- topTable(fit, n = Inf)
ids <- match(rownames(res), rownames(dev))
res$name <- rowData(dev)$name[ids]
res$rank <- rank(res$P.Value)

## TMM
colData(TMM_devs)$group_id <- substr(colnames(TMM_devs), 1, nchar(colnames(TMM_devs)) - 5)
design <- model.matrix(~ TMM_devs$group_id)
fit <- eBayes(lmFit(assays(TMM_devs)$z, design))
TMMres <- topTable(fit, n = Inf)
ids <- match(rownames(TMMres), rownames(TMM_devs))
TMMres$name <- rowData(TMM_devs)$name[ids]
TMMres$rank <- rank(TMMres$P.Value)

## GCQN
colData(gcqn_devs)$group_id <- substr(colnames(gcqn_devs), 1, nchar(colnames(gcqn_devs)) - 5)
design <- model.matrix(~ gcqn_devs$group_id)
fit <- eBayes(lmFit(assays(gcqn_devs)$z, design))
gcqn_res <- topTable(fit, n = Inf)
ids <- match(rownames(gcqn_res), rownames(gcqn_devs))
gcqn_res$name <- rowData(gcqn_devs)$name[ids]
gcqn_res$rank <- rank(gcqn_res$P.Value)

## SGCQN
colData(Sgcqn_devs)$group_id <- substr(colnames(Sgcqn_devs), 1, nchar(colnames(Sgcqn_devs)) - 5)
design <- model.matrix(~ Sgcqn_devs$group_id)
fit <- eBayes(lmFit(assays(Sgcqn_devs)$z, design))
Sgcqn_res <- topTable(fit, n = Inf)
ids <- match(rownames(Sgcqn_res), rownames(Sgcqn_devs))
Sgcqn_res$name <- rowData(Sgcqn_devs)$name[ids]
Sgcqn_res$rank <- rank(Sgcqn_res$P.Value)
```

```{r lfc compare, fig.height=7, fig.width=10}
old <- data.frame(res, method = "old")
TMM <- data.frame(TMMres, method = "TMM")
gcqn <- data.frame(gcqn_res, method = "GCQN")
Sgcqn <- data.frame(Sgcqn_res, method = "GC smooth quantile")
lfc <- do.call(rbind, list(old, TMM, gcqn, Sgcqn))
ggplot(lfc, aes(x = logFC, col = method)) + 
    facet_wrap(~ method, ncol = 2) +
    geom_histogram(aes(y = after_stat(density)),      
        fill = "white",
        bins = 30,
        alpha = 0.2) +
    geom_density(alpha = 0.2) +
    geom_vline(xintercept = 0, linetype="dashed", 
                  color = "black", size=0.5, alpha = 0.8)
```

### MA plot


::: {.panel-tabset}
### old
```{r ma, fig.height=5, fig.width=10}
colnames(lfc)[c(1,2,5)] <- c("log2FoldChange", "baseMeanLog2", "padj")
nlfc <- lfc[lfc$method == "TMM",]
olfc <- lfc[lfc$method == "old",]
ggmaplot(olfc, dr = 0.05, fc = 2, size = 0.4,
     palette = c("#B31B21", "#1465AC", "darkgray"),
     genenames = as.vector(olfc$name),
     legend = "top", top = 20,
     font.label = c("bold", 11),
     font.legend = "bold",
     font.main = "bold",
     ggtheme = ggplot2::theme_minimal()) 
```

### TMM
```{r ma TMM, fig.height=5, fig.width=10} 
ggmaplot(nlfc, dr = 0.05, fc = 2, size = 0.4,
     palette = c("#B31B21", "#1465AC", "darkgray"),
     genenames = as.vector(nlfc$name),
     legend = "top", top = 20,
     font.label = c("bold", 11),
     font.legend = "bold",
     font.main = "bold",
     ggtheme = ggplot2::theme_minimal()) 
```

### GCQN
```{r}
glfc <- lfc[lfc$method == "GCQN",]
slfc <- lfc[lfc$method == "GC smooth quantile",]
ggmaplot(glfc, dr = 0.05, fc = 2, size = 0.4,
     palette = c("#B31B21", "#1465AC", "darkgray"),
     genenames = as.vector(nlfc$name),
     legend = "top", top = 20,
     font.label = c("bold", 11),
     font.legend = "bold",
     font.main = "bold",
     ggtheme = ggplot2::theme_minimal()) 
```

### GC smooth quantile
```{r}
ggmaplot(slfc, dr = 0.05, fc = 2, size = 0.4,
     palette = c("#B31B21", "#1465AC", "darkgray"),
     genenames = as.vector(nlfc$name),
     legend = "top", top = 20,
     font.label = c("bold", 11),
     font.legend = "bold",
     font.main = "bold",
     ggtheme = ggplot2::theme_minimal()) 
```

:::

